# Generated by Django 4.2.4 on 2023-08-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_proyecto_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='fecha_creacion',
            new_name='date_of_creation',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='descripsion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='tecnologia',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='titulo',
            new_name='title',
        ),
    ]
